import type { BracketResult } from "./sportsdb";

export const HISTORICAL_DATA: Record<string, BracketResult> = {
  "2018": {
    byStage: {
      R32: [],
      R16: [
        {
          idEvent: "576424",
          strEvent: "Uruguay vs Portugal",
          strHomeTeam: "Uruguay",
          strAwayTeam: "Portugal",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-06-30",
          strTime: "21:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "576426",
          strEvent: "France vs Argentina",
          strHomeTeam: "France",
          strAwayTeam: "Argentina",
          intHomeScore: "4",
          intAwayScore: "3",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-06-30",
          strTime: "17:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "576425",
          strEvent: "Spain vs Russia",
          strHomeTeam: "Spain",
          strAwayTeam: "Russia",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-01",
          strTime: "17:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "4",
        },
        {
          idEvent: "576464",
          strEvent: "Croatia vs Denmark",
          strHomeTeam: "Croatia",
          strAwayTeam: "Denmark",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-01",
          strTime: "21:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "2",
        },
        {
          idEvent: "576465",
          strEvent: "Brazil vs Mexico",
          strHomeTeam: "Brazil",
          strAwayTeam: "Mexico",
          intHomeScore: "2",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-02",
          strTime: "18:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "576468",
          strEvent: "Belgium vs Japan",
          strHomeTeam: "Belgium",
          strAwayTeam: "Japan",
          intHomeScore: "3",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-02",
          strTime: "21:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "576466",
          strEvent: "Sweden vs Switzerland",
          strHomeTeam: "Sweden",
          strAwayTeam: "Switzerland",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-03",
          strTime: "17:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "576467",
          strEvent: "Colombia vs England",
          strHomeTeam: "Colombia",
          strAwayTeam: "England",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-03",
          strTime: "00:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "4",
        },
      ],
      QF: [
        {
          idEvent: "576469",
          strEvent: "Uruguay vs France",
          strHomeTeam: "Uruguay",
          strAwayTeam: "France",
          intHomeScore: "0",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-06",
          strTime: "17:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "576854",
          strEvent: "Brazil vs Belgium",
          strHomeTeam: "Brazil",
          strAwayTeam: "Belgium",
          intHomeScore: "1",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-06",
          strTime: "21:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "576850",
          strEvent: "Russia vs Croatia",
          strHomeTeam: "Russia",
          strAwayTeam: "Croatia",
          intHomeScore: "2",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-07",
          strTime: "21:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "4",
        },
        {
          idEvent: "576856",
          strEvent: "Sweden vs England",
          strHomeTeam: "Sweden",
          strAwayTeam: "England",
          intHomeScore: "0",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-07",
          strTime: "18:00:00",
          strStatus: "FT",
        },
      ],
      SF: [
        {
          idEvent: "576962",
          strEvent: "France vs Belgium",
          strHomeTeam: "France",
          strAwayTeam: "Belgium",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-10",
          strTime: "21:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "576963",
          strEvent: "Croatia vs England",
          strHomeTeam: "Croatia",
          strAwayTeam: "England",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-11",
          strTime: "21:00:00",
          strStatus: "FT",
        },
      ],
      F: [
        {
          idEvent: "577207",
          strEvent: "France vs Croatia",
          strHomeTeam: "France",
          strAwayTeam: "Croatia",
          intHomeScore: "4",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-15",
          strTime: "18:00:00",
          strStatus: "FT",
        },
      ],
    },
    failedStages: [],
  },
  "2022": {
    byStage: {
      R32: [],
      R16: [
        {
          idEvent: "1665048",
          strEvent: "Netherlands vs USA",
          strHomeTeam: "Netherlands",
          strAwayTeam: "USA",
          intHomeScore: "3",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-03",
          strTime: "15:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1665112",
          strEvent: "Argentina vs Australia",
          strHomeTeam: "Argentina",
          strAwayTeam: "Australia",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-03",
          strTime: "19:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1665049",
          strEvent: "England vs Senegal",
          strHomeTeam: "England",
          strAwayTeam: "Senegal",
          intHomeScore: "3",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-04",
          strTime: "19:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1665113",
          strEvent: "France vs Poland",
          strHomeTeam: "France",
          strAwayTeam: "Poland",
          intHomeScore: "3",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-04",
          strTime: "15:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1665565",
          strEvent: "Japan vs Croatia",
          strHomeTeam: "Japan",
          strAwayTeam: "Croatia",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-05",
          strTime: "15:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "1",
          intAwayPenaltyScore: "3",
        },
        {
          idEvent: "1665657",
          strEvent: "Brazil vs South Korea",
          strHomeTeam: "Brazil",
          strAwayTeam: "South Korea",
          intHomeScore: "4",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-05",
          strTime: "19:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1665566",
          strEvent: "Morocco vs Spain",
          strHomeTeam: "Morocco",
          strAwayTeam: "Spain",
          intHomeScore: "0",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-06",
          strTime: "15:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "0",
        },
        {
          idEvent: "1665658",
          strEvent: "Portugal vs Switzerland",
          strHomeTeam: "Portugal",
          strAwayTeam: "Switzerland",
          intHomeScore: "6",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-06",
          strTime: "19:00:00",
          strStatus: "FT",
        },
      ],
      QF: [
        {
          idEvent: "1665716",
          strEvent: "Netherlands vs Argentina",
          strHomeTeam: "Netherlands",
          strAwayTeam: "Argentina",
          intHomeScore: "2",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-09",
          strTime: "19:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "4",
        },
        {
          idEvent: "1665817",
          strEvent: "Croatia vs Brazil",
          strHomeTeam: "Croatia",
          strAwayTeam: "Brazil",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-09",
          strTime: "15:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "4",
          intAwayPenaltyScore: "2",
        },
        {
          idEvent: "1665794",
          strEvent: "England vs France",
          strHomeTeam: "England",
          strAwayTeam: "France",
          intHomeScore: "1",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-10",
          strTime: "19:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1665834",
          strEvent: "Morocco vs Portugal",
          strHomeTeam: "Morocco",
          strAwayTeam: "Portugal",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-10",
          strTime: "15:00:00",
          strStatus: "FT",
        },
      ],
      SF: [
        {
          idEvent: "1666028",
          strEvent: "Argentina vs Croatia",
          strHomeTeam: "Argentina",
          strAwayTeam: "Croatia",
          intHomeScore: "3",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-13",
          strTime: "19:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1666049",
          strEvent: "France vs Morocco",
          strHomeTeam: "France",
          strAwayTeam: "Morocco",
          intHomeScore: "2",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-14",
          strTime: "19:00:00",
          strStatus: "FT",
        },
      ],
      F: [
        {
          idEvent: "1666948",
          strEvent: "Argentina vs France",
          strHomeTeam: "Argentina",
          strAwayTeam: "France",
          intHomeScore: "3",
          intAwayScore: "3",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-18",
          strTime: "15:00:00",
          strStatus: "AP",
          intHomePenaltyScore: "4",
          intAwayPenaltyScore: "2",
        },
      ],
    },
    failedStages: [],
  },
  "2014": {
    byStage: {
      R32: [],
      R16: [
        {
          idEvent: "505634",
          strEvent: "Brazil vs Chile",
          strHomeTeam: "Brazil",
          strAwayTeam: "Chile",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-06-28",
          strTime: "00:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "2",
        },
        {
          idEvent: "505635",
          strEvent: "Colombia vs Uruguay",
          strHomeTeam: "Colombia",
          strAwayTeam: "Uruguay",
          intHomeScore: "2",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-06-28",
          strTime: "17:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "505636",
          strEvent: "Netherlands vs Mexico",
          strHomeTeam: "Netherlands",
          strAwayTeam: "Mexico",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-06-29",
          strTime: "13:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "505637",
          strEvent: "Costa Rica vs Greece",
          strHomeTeam: "Costa Rica",
          strAwayTeam: "Greece",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-06-29",
          strTime: "17:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "5",
          intAwayPenaltyScore: "3",
        },
        {
          idEvent: "505638",
          strEvent: "France vs Nigeria",
          strHomeTeam: "France",
          strAwayTeam: "Nigeria",
          intHomeScore: "2",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-06-30",
          strTime: "13:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "505639",
          strEvent: "Germany vs Algeria",
          strHomeTeam: "Germany",
          strAwayTeam: "Algeria",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-06-30",
          strTime: "17:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "505640",
          strEvent: "Argentina vs Switzerland",
          strHomeTeam: "Argentina",
          strAwayTeam: "Switzerland",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-07-01",
          strTime: "13:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "505641",
          strEvent: "Belgium vs USA",
          strHomeTeam: "Belgium",
          strAwayTeam: "USA",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-07-01",
          strTime: "17:00:00",
          strStatus: "FT",
        },
      ],
      QF: [
        {
          idEvent: "505642",
          strEvent: "France vs Germany",
          strHomeTeam: "France",
          strAwayTeam: "Germany",
          intHomeScore: "0",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-07-04",
          strTime: "13:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "505643",
          strEvent: "Brazil vs Colombia",
          strHomeTeam: "Brazil",
          strAwayTeam: "Colombia",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-07-04",
          strTime: "17:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "505644",
          strEvent: "Argentina vs Belgium",
          strHomeTeam: "Argentina",
          strAwayTeam: "Belgium",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-07-05",
          strTime: "13:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "505645",
          strEvent: "Netherlands vs Costa Rica",
          strHomeTeam: "Netherlands",
          strAwayTeam: "Costa Rica",
          intHomeScore: "0",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-07-05",
          strTime: "17:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "4",
          intAwayPenaltyScore: "3",
        },
      ],
      SF: [
        {
          idEvent: "505646",
          strEvent: "Brazil vs Germany",
          strHomeTeam: "Brazil",
          strAwayTeam: "Germany",
          intHomeScore: "1",
          intAwayScore: "7",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-07-08",
          strTime: "17:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "505647",
          strEvent: "Netherlands vs Argentina",
          strHomeTeam: "Netherlands",
          strAwayTeam: "Argentina",
          intHomeScore: "0",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-07-09",
          strTime: "17:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "2",
          intAwayPenaltyScore: "4",
        },
      ],
      F: [
        {
          idEvent: "505649",
          strEvent: "Germany vs Argentina",
          strHomeTeam: "Germany",
          strAwayTeam: "Argentina",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-07-13",
          strTime: "19:00:00",
          strStatus: "FT",
        },
      ],
    },
    failedStages: [],
  },
  "2010": {
    byStage: {
      R32: [],
      R16: [
        {
          idEvent: "538305",
          strEvent: "Uruguay vs South Korea",
          strHomeTeam: "Uruguay",
          strAwayTeam: "South Korea",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-06-26",
          strTime: "16:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "538319",
          strEvent: "USA vs Ghana",
          strHomeTeam: "USA",
          strAwayTeam: "Ghana",
          intHomeScore: "1",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-06-26",
          strTime: "20:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "538325",
          strEvent: "Netherlands vs Slovakia",
          strHomeTeam: "Netherlands",
          strAwayTeam: "Slovakia",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-06-28",
          strTime: "16:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "538329",
          strEvent: "Brazil vs Chile",
          strHomeTeam: "Brazil",
          strAwayTeam: "Chile",
          intHomeScore: "3",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-06-28",
          strTime: "20:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "538307",
          strEvent: "Argentina vs Mexico",
          strHomeTeam: "Argentina",
          strAwayTeam: "Mexico",
          intHomeScore: "3",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-06-27",
          strTime: "20:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "538306",
          strEvent: "Germany vs England",
          strHomeTeam: "Germany",
          strAwayTeam: "England",
          intHomeScore: "4",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-06-27",
          strTime: "16:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1033973",
          strEvent: "Paraguay vs Japan",
          strHomeTeam: "Paraguay",
          strAwayTeam: "Japan",
          intHomeScore: "0",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-06-29",
          strTime: "14:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "5",
          intAwayPenaltyScore: "3",
        },
        {
          idEvent: "538308",
          strEvent: "Spain vs Portugal",
          strHomeTeam: "Spain",
          strAwayTeam: "Portugal",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-06-29",
          strTime: "20:30:00",
          strStatus: "FT",
        },
      ],
      QF: [
        {
          idEvent: "538320",
          strEvent: "Uruguay vs Ghana",
          strHomeTeam: "Uruguay",
          strAwayTeam: "Ghana",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-07-02",
          strTime: "20:30:00",
          strStatus: "FT",
          intHomePenaltyScore: "4",
          intAwayPenaltyScore: "2",
        },
        {
          idEvent: "538309",
          strEvent: "Netherlands vs Brazil",
          strHomeTeam: "Netherlands",
          strAwayTeam: "Brazil",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-07-02",
          strTime: "16:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "538310",
          strEvent: "Argentina vs Germany",
          strHomeTeam: "Argentina",
          strAwayTeam: "Germany",
          intHomeScore: "0",
          intAwayScore: "4",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-07-03",
          strTime: "16:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1033974",
          strEvent: "Paraguay vs Spain",
          strHomeTeam: "Paraguay",
          strAwayTeam: "Spain",
          intHomeScore: "0",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-07-03",
          strTime: "18:30:00",
          strStatus: "FT",
        },
      ],
      SF: [
        {
          idEvent: "538311",
          strEvent: "Uruguay vs Netherlands",
          strHomeTeam: "Uruguay",
          strAwayTeam: "Netherlands",
          intHomeScore: "2",
          intAwayScore: "3",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-07-06",
          strTime: "20:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "538312",
          strEvent: "Germany vs Spain",
          strHomeTeam: "Germany",
          strAwayTeam: "Spain",
          intHomeScore: "0",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-07-07",
          strTime: "20:30:00",
          strStatus: "FT",
        },
      ],
      F: [
        {
          idEvent: "538314",
          strEvent: "Netherlands vs Spain",
          strHomeTeam: "Netherlands",
          strAwayTeam: "Spain",
          intHomeScore: "0",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-07-11",
          strTime: "20:30:00",
          strStatus: "FT",
        },
      ],
    },
    failedStages: [],
  },
  "2006": {
    byStage: {
      R32: [],
      R16: [
        {
          idEvent: "1034683",
          strEvent: "Germany vs Sweden",
          strHomeTeam: "Germany",
          strAwayTeam: "Sweden",
          intHomeScore: "2",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2006-06-24",
          strTime: "15:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034684",
          strEvent: "Argentina vs Mexico",
          strHomeTeam: "Argentina",
          strAwayTeam: "Mexico",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2006-06-24",
          strTime: "19:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034687",
          strEvent: "Italy vs Australia",
          strHomeTeam: "Italy",
          strAwayTeam: "Australia",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2006-06-26",
          strTime: "15:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034688",
          strEvent: "Switzerland vs Ukraine",
          strHomeTeam: "Switzerland",
          strAwayTeam: "Ukraine",
          intHomeScore: "0",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2006-06-26",
          strTime: "19:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "0",
          intAwayPenaltyScore: "3",
        },
        {
          idEvent: "1034685",
          strEvent: "England vs Ecuador",
          strHomeTeam: "England",
          strAwayTeam: "Ecuador",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2006-06-25",
          strTime: "15:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034686",
          strEvent: "Portugal vs Netherlands",
          strHomeTeam: "Portugal",
          strAwayTeam: "Netherlands",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2006-06-25",
          strTime: "19:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034689",
          strEvent: "Brazil vs Ghana",
          strHomeTeam: "Brazil",
          strAwayTeam: "Ghana",
          intHomeScore: "3",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2006-06-27",
          strTime: "15:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034690",
          strEvent: "Spain vs France",
          strHomeTeam: "Spain",
          strAwayTeam: "France",
          intHomeScore: "1",
          intAwayScore: "3",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2006-06-27",
          strTime: "19:00:00",
          strStatus: "FT",
        },
      ],
      QF: [
        {
          idEvent: "1034691",
          strEvent: "Germany vs Argentina",
          strHomeTeam: "Germany",
          strAwayTeam: "Argentina",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2006-06-30",
          strTime: "15:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "4",
          intAwayPenaltyScore: "2",
        },
        {
          idEvent: "1034692",
          strEvent: "Italy vs Ukraine",
          strHomeTeam: "Italy",
          strAwayTeam: "Ukraine",
          intHomeScore: "3",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2006-06-30",
          strTime: "19:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034693",
          strEvent: "England vs Portugal",
          strHomeTeam: "England",
          strAwayTeam: "Portugal",
          intHomeScore: "0",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2006-07-01",
          strTime: "15:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "1",
          intAwayPenaltyScore: "3",
        },
        {
          idEvent: "1034694",
          strEvent: "Brazil vs France",
          strHomeTeam: "Brazil",
          strAwayTeam: "France",
          intHomeScore: "0",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2006-07-01",
          strTime: "19:00:00",
          strStatus: "FT",
        },
      ],
      SF: [
        {
          idEvent: "1034695",
          strEvent: "Germany vs Italy",
          strHomeTeam: "Germany",
          strAwayTeam: "Italy",
          intHomeScore: "0",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2006-07-04",
          strTime: "19:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034696",
          strEvent: "Portugal vs France",
          strHomeTeam: "Portugal",
          strAwayTeam: "France",
          intHomeScore: "0",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2006-07-05",
          strTime: "19:00:00",
          strStatus: "FT",
        },
      ],
      F: [
        {
          idEvent: "1034698",
          strEvent: "Italy vs France",
          strHomeTeam: "Italy",
          strAwayTeam: "France",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2006-07-09",
          strTime: "18:00:00",
          strStatus: "AP",
          intHomePenaltyScore: "5",
          intAwayPenaltyScore: "3",
        },
      ],
    },
    failedStages: [],
  },
  "2002": {
    byStage: {
      R32: [],
      R16: [
        {
          idEvent: "1034620",
          strEvent: "Germany vs Paraguay",
          strHomeTeam: "Germany",
          strAwayTeam: "Paraguay",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2002-06-15",
          strTime: "06:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034624",
          strEvent: "Mexico vs USA",
          strHomeTeam: "Mexico",
          strAwayTeam: "USA",
          intHomeScore: "0",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2002-06-17",
          strTime: "06:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034621",
          strEvent: "Spain vs Ireland",
          strHomeTeam: "Spain",
          strAwayTeam: "Ireland",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2002-06-16",
          strTime: "11:30:00",
          strStatus: "AP",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "2",
        },
        {
          idEvent: "1034626",
          strEvent: "South Korea vs Italy",
          strHomeTeam: "South Korea",
          strAwayTeam: "Italy",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2002-06-18",
          strTime: "11:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034619",
          strEvent: "Denmark vs England",
          strHomeTeam: "Denmark",
          strAwayTeam: "England",
          intHomeScore: "0",
          intAwayScore: "3",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2002-06-15",
          strTime: "11:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034623",
          strEvent: "Brazil vs Belgium",
          strHomeTeam: "Brazil",
          strAwayTeam: "Belgium",
          intHomeScore: "2",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2002-06-17",
          strTime: "11:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034622",
          strEvent: "Sweden vs Senegal",
          strHomeTeam: "Sweden",
          strAwayTeam: "Senegal",
          intHomeScore: "1",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2002-06-16",
          strTime: "06:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034625",
          strEvent: "Japan vs Turkey",
          strHomeTeam: "Japan",
          strAwayTeam: "Turkey",
          intHomeScore: "0",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2002-06-18",
          strTime: "06:30:00",
          strStatus: "FT",
        },
      ],
      QF: [
        {
          idEvent: "1034628",
          strEvent: "Germany vs USA",
          strHomeTeam: "Germany",
          strAwayTeam: "USA",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2002-06-21",
          strTime: "11:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034630",
          strEvent: "Spain vs South Korea",
          strHomeTeam: "Spain",
          strAwayTeam: "South Korea",
          intHomeScore: "0",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2002-06-22",
          strTime: "06:30:00",
          strStatus: "AP",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "5",
        },
        {
          idEvent: "1034627",
          strEvent: "England vs Brazil",
          strHomeTeam: "England",
          strAwayTeam: "Brazil",
          intHomeScore: "1",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2002-06-21",
          strTime: "06:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034629",
          strEvent: "Senegal vs Turkey",
          strHomeTeam: "Senegal",
          strAwayTeam: "Turkey",
          intHomeScore: "0",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2002-06-22",
          strTime: "11:30:00",
          strStatus: "FT",
        },
      ],
      SF: [
        {
          idEvent: "1034631",
          strEvent: "Germany vs South Korea",
          strHomeTeam: "Germany",
          strAwayTeam: "South Korea",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2002-06-25",
          strTime: "11:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034632",
          strEvent: "Brazil vs Turkey",
          strHomeTeam: "Brazil",
          strAwayTeam: "Turkey",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2002-06-26",
          strTime: "11:30:00",
          strStatus: "FT",
        },
      ],
      F: [
        {
          idEvent: "1034634",
          strEvent: "Germany vs Brazil",
          strHomeTeam: "Germany",
          strAwayTeam: "Brazil",
          intHomeScore: "0",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2002-06-30",
          strTime: "11:00:00",
          strStatus: "FT",
        },
      ],
    },
    failedStages: [],
  },
  "1998": {
    byStage: {
      R32: [],
      R16: [
        {
          idEvent: "1034555",
          strEvent: "Italy vs Norway",
          strHomeTeam: "Italy",
          strAwayTeam: "Norway",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1998-06-27",
          strTime: "14:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034556",
          strEvent: "Brazil vs Chile",
          strHomeTeam: "Brazil",
          strAwayTeam: "Chile",
          intHomeScore: "4",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1998-06-27",
          strTime: "19:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034557",
          strEvent: "France vs Paraguay",
          strHomeTeam: "France",
          strAwayTeam: "Paraguay",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1998-06-28",
          strTime: "14:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034558",
          strEvent: "Nigeria vs Denmark",
          strHomeTeam: "Nigeria",
          strAwayTeam: "Denmark",
          intHomeScore: "1",
          intAwayScore: "4",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1998-06-28",
          strTime: "19:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034559",
          strEvent: "Germany vs Mexico",
          strHomeTeam: "Germany",
          strAwayTeam: "Mexico",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1998-06-29",
          strTime: "14:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "1036353",
          strEvent: "Netherlands vs FR Yugoslavia",
          strHomeTeam: "Netherlands",
          strAwayTeam: "FR Yugoslavia",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1998-06-29",
          strTime: "19:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034561",
          strEvent: "Romania vs Croatia",
          strHomeTeam: "Romania",
          strAwayTeam: "Croatia",
          intHomeScore: "0",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1998-06-30",
          strTime: "14:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034562",
          strEvent: "Argentina vs England",
          strHomeTeam: "Argentina",
          strAwayTeam: "England",
          intHomeScore: "2",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1998-06-30",
          strTime: "19:00:00",
          strStatus: "AP",
          intHomePenaltyScore: "4",
          intAwayPenaltyScore: "3",
        },
      ],
      QF: [
        {
          idEvent: "1034563",
          strEvent: "Italy vs France",
          strHomeTeam: "Italy",
          strAwayTeam: "France",
          intHomeScore: "0",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1998-07-03",
          strTime: "14:30:00",
          strStatus: "AP",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "4",
        },
        {
          idEvent: "1034564",
          strEvent: "Brazil vs Denmark",
          strHomeTeam: "Brazil",
          strAwayTeam: "Denmark",
          intHomeScore: "3",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1998-07-03",
          strTime: "19:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034565",
          strEvent: "Netherlands vs Argentina",
          strHomeTeam: "Netherlands",
          strAwayTeam: "Argentina",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1998-07-04",
          strTime: "14:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "1034566",
          strEvent: "Germany vs Croatia",
          strHomeTeam: "Germany",
          strAwayTeam: "Croatia",
          intHomeScore: "0",
          intAwayScore: "3",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1998-07-04",
          strTime: "19:00:00",
          strStatus: "FT",
        },
      ],
      SF: [
        {
          idEvent: "1034567",
          strEvent: "Brazil vs Netherlands",
          strHomeTeam: "Brazil",
          strAwayTeam: "Netherlands",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1998-07-07",
          strTime: "19:00:00",
          strStatus: "AP",
          intHomePenaltyScore: "4",
          intAwayPenaltyScore: "2",
        },
        {
          idEvent: "1034568",
          strEvent: "France vs Croatia",
          strHomeTeam: "France",
          strAwayTeam: "Croatia",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1998-07-08",
          strTime: "19:00:00",
          strStatus: "FT",
        },
      ],
      F: [
        {
          idEvent: "1034570",
          strEvent: "Brazil vs France",
          strHomeTeam: "Brazil",
          strAwayTeam: "France",
          intHomeScore: "0",
          intAwayScore: "3",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1998-07-12",
          strTime: "19:00:00",
          strStatus: "FT",
        },
      ],
    },
    failedStages: [],
  },
  "1994": {
    byStage: {
      R32: [],
      R16: [
        {
          idEvent: "199401",
          strEvent: "Germany vs Belgium",
          strHomeTeam: "Germany",
          strAwayTeam: "Belgium",
          intHomeScore: "3",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1994-07-02",
          strTime: "12:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Völler 6', 38'; Klinsmann 11'",
          strAwayGoalDetails: "Grün 8'; Albert 90'",
        },
        {
          idEvent: "199402",
          strEvent: "Mexico vs Bulgaria",
          strHomeTeam: "Mexico",
          strAwayTeam: "Bulgaria",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1994-07-05",
          strTime: "16:30:00",
          strStatus: "AP",
          intHomePenaltyScore: "1",
          intAwayPenaltyScore: "3",
          strHomeGoalDetails: "García Aspe 18' (pen)",
          strAwayGoalDetails: "Stoichkov 6'",
        },
        {
          idEvent: "199403",
          strEvent: "Spain vs Switzerland",
          strHomeTeam: "Spain",
          strAwayTeam: "Switzerland",
          intHomeScore: "3",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1994-07-02",
          strTime: "16:30:00",
          strStatus: "FT",
          strHomeGoalDetails: "Hierro 15'; Luis Enrique 74'; Begiristain 86' (pen)",
          strAwayGoalDetails: null,
        },
        {
          idEvent: "199404",
          strEvent: "Nigeria vs Italy",
          strHomeTeam: "Nigeria",
          strAwayTeam: "Italy",
          intHomeScore: "1",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1994-07-05",
          strTime: "13:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Amunike 25'",
          strAwayGoalDetails: "R. Baggio 88', 102' (pen)",
        },
        {
          idEvent: "199405",
          strEvent: "Saudi Arabia vs Sweden",
          strHomeTeam: "Saudi Arabia",
          strAwayTeam: "Sweden",
          intHomeScore: "1",
          intAwayScore: "3",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1994-07-03",
          strTime: "12:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Al-Ghesheyan 85'",
          strAwayGoalDetails: "Dahlin 6'; K. Andersson 51', 88'",
        },
        {
          idEvent: "199406",
          strEvent: "Romania vs Argentina",
          strHomeTeam: "Romania",
          strAwayTeam: "Argentina",
          intHomeScore: "3",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1994-07-03",
          strTime: "13:30:00",
          strStatus: "FT",
          strHomeGoalDetails: "Dumitrescu 11', 18'; Hagi 58'",
          strAwayGoalDetails: "Batistuta 16' (pen); Balbo 75'",
        },
        {
          idEvent: "199407",
          strEvent: "Netherlands vs Republic of Ireland",
          strHomeTeam: "Netherlands",
          strAwayTeam: "Republic of Ireland",
          intHomeScore: "2",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1994-07-04",
          strTime: "12:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Bergkamp 11'; Jonk 41'",
          strAwayGoalDetails: null,
        },
        {
          idEvent: "199408",
          strEvent: "Brazil vs USA",
          strHomeTeam: "Brazil",
          strAwayTeam: "USA",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1994-07-04",
          strTime: "12:30:00",
          strStatus: "FT",
          strHomeGoalDetails: "Bebeto 72'",
          strAwayGoalDetails: null,
        },
      ],
      QF: [
        {
          idEvent: "199409",
          strEvent: "Bulgaria vs Germany",
          strHomeTeam: "Bulgaria",
          strAwayTeam: "Germany",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1994-07-10",
          strTime: "12:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Stoichkov 75'; Letchkov 78'",
          strAwayGoalDetails: "Matthäus 47' (pen)",
        },
        {
          idEvent: "199410",
          strEvent: "Italy vs Spain",
          strHomeTeam: "Italy",
          strAwayTeam: "Spain",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1994-07-09",
          strTime: "12:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "D. Baggio 25'; R. Baggio 88'",
          strAwayGoalDetails: "Caminero 58'",
        },
        {
          idEvent: "199411",
          strEvent: "Romania vs Sweden",
          strHomeTeam: "Romania",
          strAwayTeam: "Sweden",
          intHomeScore: "2",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1994-07-10",
          strTime: "12:30:00",
          strStatus: "AP",
          intHomePenaltyScore: "4",
          intAwayPenaltyScore: "5",
          strHomeGoalDetails: "Răducioiu 88', 101'",
          strAwayGoalDetails: "Brolin 78'; K. Andersson 115'",
        },
        {
          idEvent: "199412",
          strEvent: "Netherlands vs Brazil",
          strHomeTeam: "Netherlands",
          strAwayTeam: "Brazil",
          intHomeScore: "2",
          intAwayScore: "3",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1994-07-09",
          strTime: "14:30:00",
          strStatus: "FT",
          strHomeGoalDetails: "Bergkamp 64'; Winter 76'",
          strAwayGoalDetails: "Romário 53'; Bebeto 63'; Branco 81'",
        },
      ],
      SF: [
        {
          idEvent: "199413",
          strEvent: "Bulgaria vs Italy",
          strHomeTeam: "Bulgaria",
          strAwayTeam: "Italy",
          intHomeScore: "1",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1994-07-13",
          strTime: "16:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Stoichkov 44' (pen)",
          strAwayGoalDetails: "R. Baggio 21', 25'",
        },
        {
          idEvent: "199414",
          strEvent: "Sweden vs Brazil",
          strHomeTeam: "Sweden",
          strAwayTeam: "Brazil",
          intHomeScore: "0",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1994-07-13",
          strTime: "16:30:00",
          strStatus: "FT",
          strHomeGoalDetails: null,
          strAwayGoalDetails: "Romário 80'",
        },
      ],
      F: [
        {
          idEvent: "199415",
          strEvent: "Brazil vs Italy",
          strHomeTeam: "Brazil",
          strAwayTeam: "Italy",
          intHomeScore: "0",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1994-07-17",
          strTime: "12:30:00",
          strStatus: "AP",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "2",
          strHomeGoalDetails: null,
          strAwayGoalDetails: null,
        },
      ],
    },
    failedStages: [],
  },
  "1990": {
    byStage: {
      R32: [],
      R16: [
        {
          idEvent: "199001",
          strEvent: "Brazil vs Argentina",
          strHomeTeam: "Brazil",
          strAwayTeam: "Argentina",
          intHomeScore: "0",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1990-06-24",
          strTime: "17:00:00",
          strStatus: "FT",
          strHomeGoalDetails: null,
          strAwayGoalDetails: "Caniggia 81'",
        },
        {
          idEvent: "199002",
          strEvent: "Spain vs Yugoslavia",
          strHomeTeam: "Spain",
          strAwayTeam: "Yugoslavia",
          intHomeScore: "1",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1990-06-26",
          strTime: "17:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Salinas 84'",
          strAwayGoalDetails: "Stojković 78', 93'",
        },
        {
          idEvent: "199003",
          strEvent: "Republic of Ireland vs Romania",
          strHomeTeam: "Republic of Ireland",
          strAwayTeam: "Romania",
          intHomeScore: "0",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1990-06-25",
          strTime: "17:00:00",
          strStatus: "AP",
          intHomePenaltyScore: "5",
          intAwayPenaltyScore: "4",
          strHomeGoalDetails: null,
          strAwayGoalDetails: null,
        },
        {
          idEvent: "199004",
          strEvent: "Italy vs Uruguay",
          strHomeTeam: "Italy",
          strAwayTeam: "Uruguay",
          intHomeScore: "2",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1990-06-25",
          strTime: "21:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Schillaci 65'; Serena 83'",
          strAwayGoalDetails: null,
        },
        {
          idEvent: "199005",
          strEvent: "Czechoslovakia vs Costa Rica",
          strHomeTeam: "Czechoslovakia",
          strAwayTeam: "Costa Rica",
          intHomeScore: "4",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1990-06-23",
          strTime: "21:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Skuhravý 12', 63', 82'; Kubík 76'",
          strAwayGoalDetails: "González 55'",
        },
        {
          idEvent: "199006",
          strEvent: "West Germany vs Netherlands",
          strHomeTeam: "West Germany",
          strAwayTeam: "Netherlands",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1990-06-24",
          strTime: "21:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Klinsmann 51'; Brehme 85'",
          strAwayGoalDetails: "R. Koeman 89' (pen)",
        },
        {
          idEvent: "199007",
          strEvent: "Cameroon vs Colombia",
          strHomeTeam: "Cameroon",
          strAwayTeam: "Colombia",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1990-06-23",
          strTime: "17:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Milla 106', 108'",
          strAwayGoalDetails: "Redín 115'",
        },
        {
          idEvent: "199008",
          strEvent: "England vs Belgium",
          strHomeTeam: "England",
          strAwayTeam: "Belgium",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1990-06-26",
          strTime: "21:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Platt 119'",
          strAwayGoalDetails: null,
        },
      ],
      QF: [
        {
          idEvent: "199009",
          strEvent: "Argentina vs Yugoslavia",
          strHomeTeam: "Argentina",
          strAwayTeam: "Yugoslavia",
          intHomeScore: "0",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1990-06-30",
          strTime: "17:00:00",
          strStatus: "AP",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "2",
          strHomeGoalDetails: null,
          strAwayGoalDetails: null,
        },
        {
          idEvent: "199010",
          strEvent: "Republic of Ireland vs Italy",
          strHomeTeam: "Republic of Ireland",
          strAwayTeam: "Italy",
          intHomeScore: "0",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1990-06-30",
          strTime: "21:00:00",
          strStatus: "FT",
          strHomeGoalDetails: null,
          strAwayGoalDetails: "Schillaci 38'",
        },
        {
          idEvent: "199011",
          strEvent: "Czechoslovakia vs West Germany",
          strHomeTeam: "Czechoslovakia",
          strAwayTeam: "West Germany",
          intHomeScore: "0",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1990-07-01",
          strTime: "17:00:00",
          strStatus: "FT",
          strHomeGoalDetails: null,
          strAwayGoalDetails: "Matthäus 25' (pen)",
        },
        {
          idEvent: "199012",
          strEvent: "Cameroon vs England",
          strHomeTeam: "Cameroon",
          strAwayTeam: "England",
          intHomeScore: "2",
          intAwayScore: "3",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1990-07-01",
          strTime: "21:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Kundé 61' (pen); Ekéké 65'",
          strAwayGoalDetails: "Platt 25'; Lineker 83' (pen), 105' (pen)",
        },
      ],
      SF: [
        {
          idEvent: "199013",
          strEvent: "Argentina vs Italy",
          strHomeTeam: "Argentina",
          strAwayTeam: "Italy",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1990-07-03",
          strTime: "20:00:00",
          strStatus: "AP",
          intHomePenaltyScore: "4",
          intAwayPenaltyScore: "3",
          strHomeGoalDetails: "Caniggia 67'",
          strAwayGoalDetails: "Schillaci 17'",
        },
        {
          idEvent: "199014",
          strEvent: "West Germany vs England",
          strHomeTeam: "West Germany",
          strAwayTeam: "England",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1990-07-04",
          strTime: "20:00:00",
          strStatus: "AP",
          intHomePenaltyScore: "4",
          intAwayPenaltyScore: "3",
          strHomeGoalDetails: "Brehme 60'",
          strAwayGoalDetails: "Lineker 80'",
        },
      ],
      F: [
        {
          idEvent: "199015",
          strEvent: "West Germany vs Argentina",
          strHomeTeam: "West Germany",
          strAwayTeam: "Argentina",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1990-07-08",
          strTime: "20:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Brehme 85' (pen)",
          strAwayGoalDetails: null,
        },
      ],
    },
    failedStages: [],
  },
  "1986": {
    byStage: {
      R32: [],
      R16: [
        {
          idEvent: "198601",
          strEvent: "Brazil vs Poland",
          strHomeTeam: "Brazil",
          strAwayTeam: "Poland",
          intHomeScore: "4",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1986-06-16",
          strTime: "12:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Sócrates 30' (pen); Josimar 55'; Edinho 79'; Careca 83' (pen)",
          strAwayGoalDetails: null,
        },
        {
          idEvent: "198602",
          strEvent: "Italy vs France",
          strHomeTeam: "Italy",
          strAwayTeam: "France",
          intHomeScore: "0",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1986-06-17",
          strTime: "12:00:00",
          strStatus: "FT",
          strHomeGoalDetails: null,
          strAwayGoalDetails: "Platini 15'; Stopyra 57'",
        },
        {
          idEvent: "198603",
          strEvent: "Morocco vs West Germany",
          strHomeTeam: "Morocco",
          strAwayTeam: "West Germany",
          intHomeScore: "0",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1986-06-17",
          strTime: "16:00:00",
          strStatus: "FT",
          strHomeGoalDetails: null,
          strAwayGoalDetails: "Matthäus 88'",
        },
        {
          idEvent: "198604",
          strEvent: "Mexico vs Bulgaria",
          strHomeTeam: "Mexico",
          strAwayTeam: "Bulgaria",
          intHomeScore: "2",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1986-06-15",
          strTime: "12:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Negrete 34'; Servín 61'",
          strAwayGoalDetails: null,
        },
        {
          idEvent: "198605",
          strEvent: "Argentina vs Uruguay",
          strHomeTeam: "Argentina",
          strAwayTeam: "Uruguay",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1986-06-16",
          strTime: "16:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Pasculli 42'",
          strAwayGoalDetails: null,
        },
        {
          idEvent: "198606",
          strEvent: "England vs Paraguay",
          strHomeTeam: "England",
          strAwayTeam: "Paraguay",
          intHomeScore: "3",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1986-06-18",
          strTime: "12:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Lineker 31', 73'; Beardsley 56'",
          strAwayGoalDetails: null,
        },
        {
          idEvent: "198607",
          strEvent: "Soviet Union vs Belgium",
          strHomeTeam: "Soviet Union",
          strAwayTeam: "Belgium",
          intHomeScore: "3",
          intAwayScore: "4",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1986-06-15",
          strTime: "16:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Belanov 27', 70', 111' (pen)",
          strAwayGoalDetails: "Scifo 56'; Ceulemans 77'; Demol 102'; Claesen 110'",
        },
        {
          idEvent: "198608",
          strEvent: "Denmark vs Spain",
          strHomeTeam: "Denmark",
          strAwayTeam: "Spain",
          intHomeScore: "1",
          intAwayScore: "5",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1986-06-18",
          strTime: "16:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "J. Olsen 33' (pen)",
          strAwayGoalDetails: "Butragueño 43', 56', 80', 88' (pen); Goikoetxea 68' (pen)",
        },
      ],
      QF: [
        {
          idEvent: "198609",
          strEvent: "Brazil vs France",
          strHomeTeam: "Brazil",
          strAwayTeam: "France",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1986-06-21",
          strTime: "12:00:00",
          strStatus: "AP",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "4",
          strHomeGoalDetails: "Careca 17'",
          strAwayGoalDetails: "Platini 40'",
        },
        {
          idEvent: "198610",
          strEvent: "West Germany vs Mexico",
          strHomeTeam: "West Germany",
          strAwayTeam: "Mexico",
          intHomeScore: "0",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1986-06-21",
          strTime: "16:00:00",
          strStatus: "AP",
          intHomePenaltyScore: "4",
          intAwayPenaltyScore: "1",
          strHomeGoalDetails: null,
          strAwayGoalDetails: null,
        },
        {
          idEvent: "198611",
          strEvent: "Argentina vs England",
          strHomeTeam: "Argentina",
          strAwayTeam: "England",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1986-06-22",
          strTime: "12:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Maradona 51', 55'",
          strAwayGoalDetails: "Lineker 81'",
        },
        {
          idEvent: "198612",
          strEvent: "Spain vs Belgium",
          strHomeTeam: "Spain",
          strAwayTeam: "Belgium",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1986-06-22",
          strTime: "16:00:00",
          strStatus: "AP",
          intHomePenaltyScore: "4",
          intAwayPenaltyScore: "5",
          strHomeGoalDetails: "Señor 85'",
          strAwayGoalDetails: "Ceulemans 35'",
        },
      ],
      SF: [
        {
          idEvent: "198613",
          strEvent: "France vs West Germany",
          strHomeTeam: "France",
          strAwayTeam: "West Germany",
          intHomeScore: "0",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1986-06-25",
          strTime: "12:00:00",
          strStatus: "FT",
          strHomeGoalDetails: null,
          strAwayGoalDetails: "Brehme 9'; Völler 90'",
        },
        {
          idEvent: "198614",
          strEvent: "Argentina vs Belgium",
          strHomeTeam: "Argentina",
          strAwayTeam: "Belgium",
          intHomeScore: "2",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1986-06-25",
          strTime: "16:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Maradona 51', 63'",
          strAwayGoalDetails: null,
        },
      ],
      F: [
        {
          idEvent: "198615",
          strEvent: "Argentina vs West Germany",
          strHomeTeam: "Argentina",
          strAwayTeam: "West Germany",
          intHomeScore: "3",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1986-06-29",
          strTime: "12:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Brown 23'; Valdano 56'; Burruchaga 84'",
          strAwayGoalDetails: "Rummenigge 74'; Völler 81'",
        },
      ],
    },
    failedStages: [],
  },
  "1982": {
    byStage: {
      R32: [],
      R16: [],
      QF: [],
      SF: [
        {
          idEvent: "198201",
          strEvent: "Poland vs Italy",
          strHomeTeam: "Poland",
          strAwayTeam: "Italy",
          intHomeScore: "0",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1982-07-08",
          strTime: "17:30:00",
          strStatus: "FT",
          strHomeGoalDetails: null,
          strAwayGoalDetails: "Rossi 22', 73'",
        },
        {
          idEvent: "198202",
          strEvent: "West Germany vs France",
          strHomeTeam: "West Germany",
          strAwayTeam: "France",
          intHomeScore: "3",
          intAwayScore: "3",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1982-07-08",
          strTime: "21:00:00",
          strStatus: "AP",
          intHomePenaltyScore: "5",
          intAwayPenaltyScore: "4",
          strHomeGoalDetails: "Littbarski 17'; Rummenigge 102'; Fischer 108'",
          strAwayGoalDetails: "Platini 26' (pen); Trésor 92'; Giresse 98'",
        },
      ],
      F: [
        {
          idEvent: "198203",
          strEvent: "Italy vs West Germany",
          strHomeTeam: "Italy",
          strAwayTeam: "West Germany",
          intHomeScore: "3",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "1982-07-11",
          strTime: "20:00:00",
          strStatus: "FT",
          strHomeGoalDetails: "Rossi 57'; Tardelli 69'; Altobelli 81'",
          strAwayGoalDetails: "Breitner 83'",
        },
      ],
    },
    failedStages: [],
  },
};

