import type { BracketResult } from "./sportsdb";

export const HISTORICAL_DATA: Record<string, BracketResult> = {
  "2018": {
    byStage: {
      R32: [],
      R16: [
        {
          idEvent: "576424",
          strEvent: "Uruguay vs Portugal",
          strHomeTeam: "Uruguay",
          strAwayTeam: "Portugal",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-06-30",
          strTime: "21:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "576426",
          strEvent: "France vs Argentina",
          strHomeTeam: "France",
          strAwayTeam: "Argentina",
          intHomeScore: "4",
          intAwayScore: "3",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-06-30",
          strTime: "17:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "576425",
          strEvent: "Spain vs Russia",
          strHomeTeam: "Spain",
          strAwayTeam: "Russia",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-01",
          strTime: "17:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "4",
        },
        {
          idEvent: "576464",
          strEvent: "Croatia vs Denmark",
          strHomeTeam: "Croatia",
          strAwayTeam: "Denmark",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-01",
          strTime: "21:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "2",
        },
        {
          idEvent: "576465",
          strEvent: "Brazil vs Mexico",
          strHomeTeam: "Brazil",
          strAwayTeam: "Mexico",
          intHomeScore: "2",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-02",
          strTime: "18:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "576468",
          strEvent: "Belgium vs Japan",
          strHomeTeam: "Belgium",
          strAwayTeam: "Japan",
          intHomeScore: "3",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-02",
          strTime: "21:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "576466",
          strEvent: "Sweden vs Switzerland",
          strHomeTeam: "Sweden",
          strAwayTeam: "Switzerland",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-03",
          strTime: "17:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "576467",
          strEvent: "Colombia vs England",
          strHomeTeam: "Colombia",
          strAwayTeam: "England",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-03",
          strTime: "00:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "4",
        },
      ],
      QF: [
        {
          idEvent: "576469",
          strEvent: "Uruguay vs France",
          strHomeTeam: "Uruguay",
          strAwayTeam: "France",
          intHomeScore: "0",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-06",
          strTime: "17:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "576854",
          strEvent: "Brazil vs Belgium",
          strHomeTeam: "Brazil",
          strAwayTeam: "Belgium",
          intHomeScore: "1",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-06",
          strTime: "21:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "576850",
          strEvent: "Russia vs Croatia",
          strHomeTeam: "Russia",
          strAwayTeam: "Croatia",
          intHomeScore: "2",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-07",
          strTime: "21:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "4",
        },
        {
          idEvent: "576856",
          strEvent: "Sweden vs England",
          strHomeTeam: "Sweden",
          strAwayTeam: "England",
          intHomeScore: "0",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-07",
          strTime: "18:00:00",
          strStatus: "FT",
        },
      ],
      SF: [
        {
          idEvent: "576962",
          strEvent: "France vs Belgium",
          strHomeTeam: "France",
          strAwayTeam: "Belgium",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-10",
          strTime: "21:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "576963",
          strEvent: "Croatia vs England",
          strHomeTeam: "Croatia",
          strAwayTeam: "England",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-11",
          strTime: "21:00:00",
          strStatus: "FT",
        },
      ],
      F: [
        {
          idEvent: "577207",
          strEvent: "France vs Croatia",
          strHomeTeam: "France",
          strAwayTeam: "Croatia",
          intHomeScore: "4",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2018-07-15",
          strTime: "18:00:00",
          strStatus: "FT",
        },
      ],
    },
    failedStages: [],
  },
  "2022": {
    byStage: {
      R32: [],
      R16: [
        {
          idEvent: "1665048",
          strEvent: "Netherlands vs USA",
          strHomeTeam: "Netherlands",
          strAwayTeam: "USA",
          intHomeScore: "3",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-03",
          strTime: "15:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1665112",
          strEvent: "Argentina vs Australia",
          strHomeTeam: "Argentina",
          strAwayTeam: "Australia",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-03",
          strTime: "19:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1665049",
          strEvent: "England vs Senegal",
          strHomeTeam: "England",
          strAwayTeam: "Senegal",
          intHomeScore: "3",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-04",
          strTime: "19:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1665113",
          strEvent: "France vs Poland",
          strHomeTeam: "France",
          strAwayTeam: "Poland",
          intHomeScore: "3",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-04",
          strTime: "15:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1665565",
          strEvent: "Japan vs Croatia",
          strHomeTeam: "Japan",
          strAwayTeam: "Croatia",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-05",
          strTime: "15:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "1",
          intAwayPenaltyScore: "3",
        },
        {
          idEvent: "1665657",
          strEvent: "Brazil vs South Korea",
          strHomeTeam: "Brazil",
          strAwayTeam: "South Korea",
          intHomeScore: "4",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-05",
          strTime: "19:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1665566",
          strEvent: "Morocco vs Spain",
          strHomeTeam: "Morocco",
          strAwayTeam: "Spain",
          intHomeScore: "0",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-06",
          strTime: "15:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "0",
        },
        {
          idEvent: "1665658",
          strEvent: "Portugal vs Switzerland",
          strHomeTeam: "Portugal",
          strAwayTeam: "Switzerland",
          intHomeScore: "6",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-06",
          strTime: "19:00:00",
          strStatus: "FT",
        },
      ],
      QF: [
        {
          idEvent: "1665716",
          strEvent: "Netherlands vs Argentina",
          strHomeTeam: "Netherlands",
          strAwayTeam: "Argentina",
          intHomeScore: "2",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-09",
          strTime: "19:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "4",
        },
        {
          idEvent: "1665817",
          strEvent: "Croatia vs Brazil",
          strHomeTeam: "Croatia",
          strAwayTeam: "Brazil",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-09",
          strTime: "15:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "4",
          intAwayPenaltyScore: "2",
        },
        {
          idEvent: "1665794",
          strEvent: "England vs France",
          strHomeTeam: "England",
          strAwayTeam: "France",
          intHomeScore: "1",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-10",
          strTime: "19:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1665834",
          strEvent: "Morocco vs Portugal",
          strHomeTeam: "Morocco",
          strAwayTeam: "Portugal",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-10",
          strTime: "15:00:00",
          strStatus: "FT",
        },
      ],
      SF: [
        {
          idEvent: "1666028",
          strEvent: "Argentina vs Croatia",
          strHomeTeam: "Argentina",
          strAwayTeam: "Croatia",
          intHomeScore: "3",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-13",
          strTime: "19:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1666049",
          strEvent: "France vs Morocco",
          strHomeTeam: "France",
          strAwayTeam: "Morocco",
          intHomeScore: "2",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-14",
          strTime: "19:00:00",
          strStatus: "FT",
        },
      ],
      F: [
        {
          idEvent: "1666948",
          strEvent: "Argentina vs France",
          strHomeTeam: "Argentina",
          strAwayTeam: "France",
          intHomeScore: "3",
          intAwayScore: "3",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2022-12-18",
          strTime: "15:00:00",
          strStatus: "AP",
          intHomePenaltyScore: "4",
          intAwayPenaltyScore: "2",
        },
      ],
    },
    failedStages: [],
  },
  "2014": {
    byStage: {
      R32: [],
      R16: [
        {
          idEvent: "505634",
          strEvent: "Brazil vs Chile",
          strHomeTeam: "Brazil",
          strAwayTeam: "Chile",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-06-28",
          strTime: "00:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "3",
          intAwayPenaltyScore: "2",
        },
        {
          idEvent: "505635",
          strEvent: "Colombia vs Uruguay",
          strHomeTeam: "Colombia",
          strAwayTeam: "Uruguay",
          intHomeScore: "2",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-06-28",
          strTime: "17:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "505636",
          strEvent: "Netherlands vs Mexico",
          strHomeTeam: "Netherlands",
          strAwayTeam: "Mexico",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-06-29",
          strTime: "13:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "505637",
          strEvent: "Costa Rica vs Greece",
          strHomeTeam: "Costa Rica",
          strAwayTeam: "Greece",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-06-29",
          strTime: "17:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "5",
          intAwayPenaltyScore: "3",
        },
        {
          idEvent: "505638",
          strEvent: "France vs Nigeria",
          strHomeTeam: "France",
          strAwayTeam: "Nigeria",
          intHomeScore: "2",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-06-30",
          strTime: "13:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "505639",
          strEvent: "Germany vs Algeria",
          strHomeTeam: "Germany",
          strAwayTeam: "Algeria",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-06-30",
          strTime: "17:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "505640",
          strEvent: "Argentina vs Switzerland",
          strHomeTeam: "Argentina",
          strAwayTeam: "Switzerland",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-07-01",
          strTime: "13:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "505641",
          strEvent: "Belgium vs USA",
          strHomeTeam: "Belgium",
          strAwayTeam: "USA",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-07-01",
          strTime: "17:00:00",
          strStatus: "FT",
        },
      ],
      QF: [
        {
          idEvent: "505642",
          strEvent: "France vs Germany",
          strHomeTeam: "France",
          strAwayTeam: "Germany",
          intHomeScore: "0",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-07-04",
          strTime: "13:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "505643",
          strEvent: "Brazil vs Colombia",
          strHomeTeam: "Brazil",
          strAwayTeam: "Colombia",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-07-04",
          strTime: "17:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "505644",
          strEvent: "Argentina vs Belgium",
          strHomeTeam: "Argentina",
          strAwayTeam: "Belgium",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-07-05",
          strTime: "13:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "505645",
          strEvent: "Netherlands vs Costa Rica",
          strHomeTeam: "Netherlands",
          strAwayTeam: "Costa Rica",
          intHomeScore: "0",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-07-05",
          strTime: "17:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "4",
          intAwayPenaltyScore: "3",
        },
      ],
      SF: [
        {
          idEvent: "505646",
          strEvent: "Brazil vs Germany",
          strHomeTeam: "Brazil",
          strAwayTeam: "Germany",
          intHomeScore: "1",
          intAwayScore: "7",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-07-08",
          strTime: "17:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "505647",
          strEvent: "Netherlands vs Argentina",
          strHomeTeam: "Netherlands",
          strAwayTeam: "Argentina",
          intHomeScore: "0",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-07-09",
          strTime: "17:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "2",
          intAwayPenaltyScore: "4",
        },
      ],
      F: [
        {
          idEvent: "505649",
          strEvent: "Germany vs Argentina",
          strHomeTeam: "Germany",
          strAwayTeam: "Argentina",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2014-07-13",
          strTime: "19:00:00",
          strStatus: "FT",
        },
      ],
    },
    failedStages: [],
  },
  "2010": {
    byStage: {
      R32: [],
      R16: [
        {
          idEvent: "538305",
          strEvent: "Uruguay vs South Korea",
          strHomeTeam: "Uruguay",
          strAwayTeam: "South Korea",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-06-26",
          strTime: "16:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "538319",
          strEvent: "USA vs Ghana",
          strHomeTeam: "USA",
          strAwayTeam: "Ghana",
          intHomeScore: "1",
          intAwayScore: "2",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-06-26",
          strTime: "20:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "538325",
          strEvent: "Netherlands vs Slovakia",
          strHomeTeam: "Netherlands",
          strAwayTeam: "Slovakia",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-06-28",
          strTime: "16:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "538329",
          strEvent: "Brazil vs Chile",
          strHomeTeam: "Brazil",
          strAwayTeam: "Chile",
          intHomeScore: "3",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-06-28",
          strTime: "20:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "538307",
          strEvent: "Argentina vs Mexico",
          strHomeTeam: "Argentina",
          strAwayTeam: "Mexico",
          intHomeScore: "3",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-06-27",
          strTime: "20:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "538306",
          strEvent: "Germany vs England",
          strHomeTeam: "Germany",
          strAwayTeam: "England",
          intHomeScore: "4",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-06-27",
          strTime: "16:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1033973",
          strEvent: "Paraguay vs Japan",
          strHomeTeam: "Paraguay",
          strAwayTeam: "Japan",
          intHomeScore: "0",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-06-29",
          strTime: "14:00:00",
          strStatus: "FT",
          intHomePenaltyScore: "5",
          intAwayPenaltyScore: "3",
        },
        {
          idEvent: "538308",
          strEvent: "Spain vs Portugal",
          strHomeTeam: "Spain",
          strAwayTeam: "Portugal",
          intHomeScore: "1",
          intAwayScore: "0",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-06-29",
          strTime: "20:30:00",
          strStatus: "FT",
        },
      ],
      QF: [
        {
          idEvent: "538320",
          strEvent: "Uruguay vs Ghana",
          strHomeTeam: "Uruguay",
          strAwayTeam: "Ghana",
          intHomeScore: "1",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-07-02",
          strTime: "20:30:00",
          strStatus: "FT",
          intHomePenaltyScore: "4",
          intAwayPenaltyScore: "2",
        },
        {
          idEvent: "538309",
          strEvent: "Netherlands vs Brazil",
          strHomeTeam: "Netherlands",
          strAwayTeam: "Brazil",
          intHomeScore: "2",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-07-02",
          strTime: "16:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "538310",
          strEvent: "Argentina vs Germany",
          strHomeTeam: "Argentina",
          strAwayTeam: "Germany",
          intHomeScore: "0",
          intAwayScore: "4",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-07-03",
          strTime: "16:00:00",
          strStatus: "FT",
        },
        {
          idEvent: "1033974",
          strEvent: "Paraguay vs Spain",
          strHomeTeam: "Paraguay",
          strAwayTeam: "Spain",
          intHomeScore: "0",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-07-03",
          strTime: "18:30:00",
          strStatus: "FT",
        },
      ],
      SF: [
        {
          idEvent: "538311",
          strEvent: "Uruguay vs Netherlands",
          strHomeTeam: "Uruguay",
          strAwayTeam: "Netherlands",
          intHomeScore: "2",
          intAwayScore: "3",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-07-06",
          strTime: "20:30:00",
          strStatus: "FT",
        },
        {
          idEvent: "538312",
          strEvent: "Germany vs Spain",
          strHomeTeam: "Germany",
          strAwayTeam: "Spain",
          intHomeScore: "0",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-07-07",
          strTime: "20:30:00",
          strStatus: "FT",
        },
      ],
      F: [
        {
          idEvent: "538314",
          strEvent: "Netherlands vs Spain",
          strHomeTeam: "Netherlands",
          strAwayTeam: "Spain",
          intHomeScore: "0",
          intAwayScore: "1",
          strHomeTeamBadge: null,
          strAwayTeamBadge: null,
          dateEvent: "2010-07-11",
          strTime: "20:30:00",
          strStatus: "FT",
        },
      ],
    },
    failedStages: [],
  },
};
