import type { ByStage } from "./sportsdb";

export const STATIC_2026: ByStage = {
  "R32": [
    {
      "idEvent": "2499618",
      "strEvent": "South Africa vs Canada",
      "strHomeTeam": "South Africa",
      "strAwayTeam": "Canada",
      "intHomeScore": "0",
      "intAwayScore": "1",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/xjz9j91553368824.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/2t631f1595154867.png",
      "dateEvent": "2026-06-28",
      "strTime": "19:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": "Canada win 1-0"
    },
    {
      "idEvent": "2499835",
      "strEvent": "Brazil vs Japan",
      "strHomeTeam": "Brazil",
      "strAwayTeam": "Japan",
      "intHomeScore": "2",
      "intAwayScore": "1",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/jl6dip1726167280.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/ffsyxz1591989843.png",
      "dateEvent": "2026-06-29",
      "strTime": "17:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": "Brazil win 2-1"
    },
    {
      "idEvent": "2502846",
      "strEvent": "Germany vs Paraguay",
      "strHomeTeam": "Germany",
      "strAwayTeam": "Paraguay",
      "intHomeScore": "1",
      "intAwayScore": "1",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/1xysi51726167152.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/khgav41553419195.png",
      "dateEvent": "2026-06-29",
      "strTime": "20:30:00",
      "strStatus": "AP",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": "3",
      "intAwayScoreExtra": "4",
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": "Paraguay win 4-3 on penalties"
    },
    {
      "idEvent": "2499836",
      "strEvent": "Netherlands vs Morocco",
      "strHomeTeam": "Netherlands",
      "strAwayTeam": "Morocco",
      "intHomeScore": "1",
      "intAwayScore": "1",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/1p0hr41593787110.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/hbmwkj1731791275.png",
      "dateEvent": "2026-06-30",
      "strTime": "01:00:00",
      "strStatus": "AP",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": "2",
      "intAwayScoreExtra": "3",
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": "Morocco win 3-2 on penalties"
    },
    {
      "idEvent": "2502605",
      "strEvent": "Ivory Coast vs Norway",
      "strHomeTeam": "Ivory Coast",
      "strAwayTeam": "Norway",
      "intHomeScore": "1",
      "intAwayScore": "2",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/rwxuuu1455465643.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/gyfn811591973155.png",
      "dateEvent": "2026-06-30",
      "strTime": "17:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2502847",
      "strEvent": "France vs Sweden",
      "strHomeTeam": "France",
      "strAwayTeam": "Sweden",
      "intHomeScore": "3",
      "intAwayScore": "0",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/p3n0z51726166851.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/h5adzg1591981772.png",
      "dateEvent": "2026-06-30",
      "strTime": "21:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2503390",
      "strEvent": "Mexico vs Ecuador",
      "strHomeTeam": "Mexico",
      "strAwayTeam": "Ecuador",
      "intHomeScore": "2",
      "intAwayScore": "0",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/3rmosi1748525208.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/47wv2y1591989301.png",
      "dateEvent": "2026-07-01",
      "strTime": "01:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2503391",
      "strEvent": "England vs DR Congo",
      "strHomeTeam": "England",
      "strAwayTeam": "DR Congo",
      "intHomeScore": "2",
      "intAwayScore": "1",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/vf5ttc1726166739.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/s85jjw1728749022.png",
      "dateEvent": "2026-07-01",
      "strTime": "16:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2503392",
      "strEvent": "Belgium vs Senegal",
      "strHomeTeam": "Belgium",
      "strAwayTeam": "Senegal",
      "intHomeScore": "3",
      "intAwayScore": "2",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/8xlvxv1592062265.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/slayb01780546342.png",
      "dateEvent": "2026-07-01",
      "strTime": "20:00:00",
      "strStatus": "AET",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2499837",
      "strEvent": "USA vs Bosnia-Herzegovina",
      "strHomeTeam": "USA",
      "strAwayTeam": "Bosnia-Herzegovina",
      "intHomeScore": "2",
      "intAwayScore": "0",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/21f0oi1597948195.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/wtqqst1455463120.png",
      "dateEvent": "2026-07-02",
      "strTime": "00:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2503393",
      "strEvent": "Portugal vs Croatia",
      "strHomeTeam": "Portugal",
      "strAwayTeam": "Croatia",
      "intHomeScore": "2",
      "intAwayScore": "1",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/swqvpy1455466083.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/vvtsyu1455465317.png",
      "dateEvent": "2026-07-02",
      "strTime": "23:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2503636",
      "strEvent": "Spain vs Austria",
      "strHomeTeam": "Spain",
      "strAwayTeam": "Austria",
      "intHomeScore": "3",
      "intAwayScore": "0",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/ncgqyr1726166942.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/874p631628721400.png",
      "dateEvent": "2026-07-02",
      "strTime": "19:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2502848",
      "strEvent": "Australia vs Egypt",
      "strHomeTeam": "Australia",
      "strAwayTeam": "Egypt",
      "intHomeScore": "1",
      "intAwayScore": "1",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/eylq8x1781926138.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/uheyzo1742102234.png",
      "dateEvent": "2026-07-03",
      "strTime": "18:00:00",
      "strStatus": "AP",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": "2",
      "intAwayScoreExtra": "4",
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2502849",
      "strEvent": "Argentina vs Cape Verde",
      "strHomeTeam": "Argentina",
      "strAwayTeam": "Cape Verde",
      "intHomeScore": "3",
      "intAwayScore": "2",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/3zplhu1726167477.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/5jn0o71593280376.png",
      "dateEvent": "2026-07-03",
      "strTime": "22:00:00",
      "strStatus": "AET",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2503635",
      "strEvent": "Switzerland vs Algeria",
      "strHomeTeam": "Switzerland",
      "strAwayTeam": "Algeria",
      "intHomeScore": "2",
      "intAwayScore": "0",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/mb7yqe1717365808.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/rrwpry1455460218.png",
      "dateEvent": "2026-07-03",
      "strTime": "03:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2503394",
      "strEvent": "Colombia vs Ghana",
      "strHomeTeam": "Colombia",
      "strAwayTeam": "Ghana",
      "intHomeScore": "1",
      "intAwayScore": "0",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/4ymyku1691180081.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/j589xw1751526124.png",
      "dateEvent": "2026-07-04",
      "strTime": "01:30:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    }
  ],
  "R16": [
    {
      "idEvent": "2505183",
      "strEvent": "Canada vs Morocco",
      "strHomeTeam": "Canada",
      "strAwayTeam": "Morocco",
      "intHomeScore": "0",
      "intAwayScore": "3",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/2t631f1595154867.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/hbmwkj1731791275.png",
      "dateEvent": "2026-07-04",
      "strTime": "17:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2505624",
      "strEvent": "Paraguay vs France",
      "strHomeTeam": "Paraguay",
      "strAwayTeam": "France",
      "intHomeScore": "0",
      "intAwayScore": "1",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/khgav41553419195.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/p3n0z51726166851.png",
      "dateEvent": "2026-07-04",
      "strTime": "21:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2505462",
      "strEvent": "Brazil vs Norway",
      "strHomeTeam": "Brazil",
      "strAwayTeam": "Norway",
      "intHomeScore": "1",
      "intAwayScore": "2",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/jl6dip1726167280.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/gyfn811591973155.png",
      "dateEvent": "2026-07-05",
      "strTime": "20:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2507706",
      "strEvent": "Mexico vs England",
      "strHomeTeam": "Mexico",
      "strAwayTeam": "England",
      "intHomeScore": "2",
      "intAwayScore": "3",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/3rmosi1748525208.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/vf5ttc1726166739.png",
      "dateEvent": "2026-07-06",
      "strTime": "02:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2511721",
      "strEvent": "Portugal vs Spain",
      "strHomeTeam": "Portugal",
      "strAwayTeam": "Spain",
      "intHomeScore": "0",
      "intAwayScore": "1",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/swqvpy1455466083.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/ncgqyr1726166942.png",
      "dateEvent": "2026-07-06",
      "strTime": "19:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2507707",
      "strEvent": "USA vs Belgium",
      "strHomeTeam": "USA",
      "strAwayTeam": "Belgium",
      "intHomeScore": "1",
      "intAwayScore": "4",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/21f0oi1597948195.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/8xlvxv1592062265.png",
      "dateEvent": "2026-07-07",
      "strTime": "00:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2513670",
      "strEvent": "Argentina vs Egypt",
      "strHomeTeam": "Argentina",
      "strAwayTeam": "Egypt",
      "intHomeScore": "3",
      "intAwayScore": "2",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/3zplhu1726167477.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/uheyzo1742102234.png",
      "dateEvent": "2026-07-07",
      "strTime": "16:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2513671",
      "strEvent": "Switzerland vs Colombia",
      "strHomeTeam": "Switzerland",
      "strAwayTeam": "Colombia",
      "intHomeScore": "0",
      "intAwayScore": "0",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/mb7yqe1717365808.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/4ymyku1691180081.png",
      "dateEvent": "2026-07-07",
      "strTime": "20:00:00",
      "strStatus": "AP",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": "4",
      "intAwayScoreExtra": "3",
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    }
  ],
  "QF": [
    {
      "idEvent": "2515305",
      "strEvent": "France vs Morocco",
      "strHomeTeam": "France",
      "strAwayTeam": "Morocco",
      "intHomeScore": "2",
      "intAwayScore": "0",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/p3n0z51726166851.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/hbmwkj1731791275.png",
      "dateEvent": "2026-07-09",
      "strTime": "20:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2519345",
      "strEvent": "Spain vs Belgium",
      "strHomeTeam": "Spain",
      "strAwayTeam": "Belgium",
      "intHomeScore": "2",
      "intAwayScore": "1",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/ncgqyr1726166942.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/8xlvxv1592062265.png",
      "dateEvent": "2026-07-10",
      "strTime": "19:00:00",
      "strStatus": "FT",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2517651",
      "strEvent": "Norway vs England",
      "strHomeTeam": "Norway",
      "strAwayTeam": "England",
      "intHomeScore": "1",
      "intAwayScore": "2",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/gyfn811591973155.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/vf5ttc1726166739.png",
      "dateEvent": "2026-07-11",
      "strTime": "21:00:00",
      "strStatus": "AET",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    },
    {
      "idEvent": "2520608",
      "strEvent": "Argentina vs Switzerland",
      "strHomeTeam": "Argentina",
      "strAwayTeam": "Switzerland",
      "intHomeScore": "3",
      "intAwayScore": "1",
      "strHomeTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/3zplhu1726167477.png",
      "strAwayTeamBadge": "https://r2.thesportsdb.com/images/media/team/badge/mb7yqe1717365808.png",
      "dateEvent": "2026-07-12",
      "strTime": "01:00:00",
      "strStatus": "AET",
      "strHomeGoalDetails": null,
      "strAwayGoalDetails": null,
      "intHomeScoreExtra": null,
      "intAwayScoreExtra": null,
      "intHomePenaltyScore": null,
      "intAwayPenaltyScore": null,
      "strResult": ""
    }
  ],
  "SF": [],
  "F": []
};
